repos:
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort
  - repo: https://gitlab.com/pycqa/flake8
    # Update this to the latest Flake8 version
    # https://gitlab.com/pycqa/flake8/-/tags
    rev: 3.8.4
    hooks:
    -   id: flake8
