name: unit_tests

# This is a Github Action workflow which runs the unit tests (via setup.py) whenever a
# commit is made to master

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code and install Python
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1

    # Run the unit tests
    - name: Install unit test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Run unit tests
      run: python setup.py test
